"""Dataset packaging: explode raw pipeline JSONL into per-family task files.

This module turns the upstream data pipeline's frozen ``data/final/test.jsonl``
(one row per state, each carrying one or more questions) into the
``datasets/v1/*.jsonl`` task files and ``datasets/manifest.json`` that ship
with the benchmark.

It intentionally *overwrites* ``datasets/v1/*.jsonl`` when run; those files
are FROZEN between releases, so this should only be used when rebuilding
datasets from a fresh upstream pipeline output.
"""

from __future__ import annotations

import json
import logging
from collections import defaultdict
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# License map per source (only sources permitted for redistribution in v1)
_LICENSE: dict[str, str] = {
    "massive": "CC BY 4.0",
    "banking77": "CC BY 4.0",
    "banking77+mt": "CC BY 4.0",
    "comilingua": "CC BY 4.0",
    "synthetic": "CC BY 4.0",
}

_PROVENANCE_NOTES: dict[str, str] = {
    "massive": "MASSIVE official test split",
    "banking77": "Banking77 translated to Indic via NLLB-200",
    "banking77+mt": "Banking77 translated to Indic via NLLB-200",
    "comilingua": "COMI-LINGUA Hinglish LID test split",
    "synthetic": "Synthetic enterprise data generated by cmul8 (qwen3-235b + deepseek checker)",
}


def _family_for(source: str, task_field: str | None = None) -> str:
    """Map a source (and optional task name) to a task family."""
    if source in ("massive", "banking77", "banking77+mt"):
        return "intent"
    if source == "comilingua":
        return "lid"
    if source == "synthetic":
        if task_field:
            tf = task_field.lower()
            if "score" in tf or "urgency" in tf:
                return "urgency"
            if "noul" in tf or "escalat" in tf:
                return "escalation"
        return "routing"
    return "unknown"


def _dataset_name_for(source: str, family: str) -> str:
    """Map a source/family pair to its packaged dataset file stem."""
    names = {
        "massive": "intent_massive",
        "banking77": "fintech_banking77",
        "banking77+mt": "fintech_banking77",
        "comilingua": "hinglish_lid",
        "synthetic": "synthetic_enterprise",
    }
    return names.get(source, f"{source}_{family}")


def _make_id(source: str, lang: str, row_idx: int, q_idx: int) -> str:
    """Build the canonical IndicJevBench item id."""
    src = source.replace("+", "").replace(" ", "_")
    return f"{src}-{lang}-{row_idx:04d}-q{q_idx}"


def _normalize_expected(expected: Any) -> Any:
    """Normalize a gold label to int where possible (noul bools -> 0/1)."""
    if isinstance(expected, bool):
        return int(expected)
    if isinstance(expected, str):
        low = expected.lower()
        if low == "true":
            return 1
        if low == "false":
            return 0
        try:
            return int(expected)
        except ValueError:
            return expected
    return expected


def _item_for_question(
    ex: Mapping[str, Any], source: str, lang: str, row_idx: int, q_idx: int
) -> tuple[str, dict[str, Any]] | None:
    """Build one packaged item from a raw question, or None to skip it."""
    q = ex["questions"][q_idx]
    q_type = q.get("type")
    if q_type not in ("choice", "score", "noul"):
        return None
    family = _family_for(source, q.get("task") or q.get("qid") or "")
    dataset_name = _dataset_name_for(source, family)
    license_str = _LICENSE[source]
    question_out: dict[str, Any] = {
        "type": q_type,
        "instructions": q.get("instructions", ""),
        "criteria": {},
    }
    if q_type in ("choice", "score") and q.get("options"):
        question_out["options"] = q["options"]
    expected = q.get("label")
    if expected is None:
        expected = q.get("answer")
    item = {
        "id": _make_id(source, lang, row_idx, q_idx),
        "family": family,
        "lang": lang,
        "state": ex.get("state", ""),
        "question": question_out,
        "expected": _normalize_expected(expected),
        "split": "v1",
        "source": source,
        "license": license_str,
        "provenance": {
            "origin": source,
            "license": license_str,
            "notes": _PROVENANCE_NOTES.get(source, ""),
        },
    }
    return dataset_name, item


@dataclass(frozen=True)
class DatasetPackager:
    """Explodes a raw pipeline JSONL into per-family task files plus a manifest.

    Attributes:
        data_final: Raw pipeline JSONL (one row per state, with questions).
        datasets_dir: Output directory for ``<name>.jsonl`` files (created).
        manifest_path: Output path for ``manifest.json``.

    Example:
        >>> packager = DatasetPackager(
        ...     data_final=Path("data/final/test.jsonl"),
        ...     datasets_dir=Path("datasets/v1"),
        ...     manifest_path=Path("datasets/manifest.json"),
        ... )
        >>> manifest = packager.package()
    """

    data_final: Path
    datasets_dir: Path
    manifest_path: Path

    def package(self) -> dict[str, Any]:
        """Run the packaging and write task files + manifest.

        Returns:
            The written manifest mapping.

        Raises:
            FileNotFoundError: If ``data_final`` does not exist.
            ValueError: If no items were produced.
        """
        if not self.data_final.exists():
            raise FileNotFoundError(
                f"{self.data_final} not found. Run the upstream data pipeline to produce it first."
            )
        self.datasets_dir.mkdir(parents=True, exist_ok=True)

        buckets: dict[str, list[dict[str, Any]]] = defaultdict(list)
        skipped = 0
        row_idx = 0
        with open(self.data_final, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    ex = json.loads(line)
                except json.JSONDecodeError:
                    skipped += 1
                    continue
                source = ex.get("source", "unknown")
                if source not in _PROVENANCE_NOTES:  # not permitted for redistribution
                    skipped += 1
                    continue
                lang = ex.get("lang", "unknown")
                for q_idx in range(len(ex.get("questions", []))):
                    out = _item_for_question(ex, source, lang, row_idx, q_idx)
                    if out is not None:
                        buckets[out[0]].append(out[1])
                row_idx += 1

        if not buckets:
            raise ValueError("No items produced. Check data/final/test.jsonl format.")

        splits: dict[str, dict[str, Any]] = {}
        for dataset_name, items in sorted(buckets.items()):
            out_path = self.datasets_dir / f"{dataset_name}.jsonl"
            with open(out_path, "w", encoding="utf-8") as f:
                f.writelines(json.dumps(item, ensure_ascii=False) + "\n" for item in items)
            logger.info("%s: %d items -> %s", dataset_name, len(items), out_path.name)
            splits[dataset_name] = {
                "n_items": len(items),
                "langs": sorted({i["lang"] for i in items}),
                "families": sorted({i["family"] for i in items}),
                "licenses": sorted({i["license"] for i in items}),
                "file": f"v1/{dataset_name}.jsonl",
            }

        manifest: dict[str, Any] = {
            "schema_version": 1,
            "splits": splits,
            "description": "IndicJevBench v1 — packaged from data/final/test.jsonl",
            "frozen_date": datetime.now(UTC).strftime("%Y-%m-%d"),
            "total_items": sum(len(v) for v in buckets.values()),
            "skipped_rows": skipped,
        }
        self.manifest_path.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        logger.info(
            "manifest written: %d total items, %d skipped rows",
            manifest["total_items"],
            skipped,
        )
        return manifest
